spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/book_rating
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_versioned_data: true
          batch_size: 1000
        order_updates: true
        order_inserts: true
  flyway:
    enabled: true
  batch:
    jdbc:
      schema: classpath:/springBatch/SPRING_BATCH.sql
      initialize-schema: always
      table-prefix: SPRING_BATCH.BATCH_