ALTER TABLE author
    ADD deleted BOOLEAN DEFAULT false NOT NULL;

ALTER TABLE book
    ADD deleted BOOLEAN DEFAULT false NOT NULL;

ALTER TABLE publisher
    ADD deleted BOOLEAN DEFAULT false NOT NULL;

ALTER TABLE rating
    ADD deleted BOOLEAN DEFAULT false NOT NULL;

ALTER TABLE users
    ADD deleted BOOLEAN DEFAULT false NOT NULL;